-- Insert system properties
INSERT INTO public.property (id, name, description, type, config, deletable, readonly, alias, "created_at", "updated_at", "deleted_at") VALUES ('property0001', 'ID', 'The unique identifier of the issue', 'id', NULL, false, true, 'id', NOW(), NOW(), NULL);
INSERT INTO public.property (id, name, description, type, config, deletable, readonly, alias, "created_at", "updated_at", "deleted_at") VALUES ('property0002', 'Title', 'The title of the issue', 'title', NULL, false, false, 'title', NOW(), NOW(), NULL);
INSERT INTO public.property (id, name, description, type, config, deletable, readonly, alias, "created_at", "updated_at", "deleted_at") VALUES ('property0003', 'Status', 'Status of the issue', 'status', '{"initialStatusId":"todo","statuses":[{"id":"todo","label":"Todo","icon":"Circle"},{"id":"queued","label":"Queued","icon":"Clock3"},{"id":"planning","label":"Planning","icon":"FileText"},{"id":"needs_clarification","label":"Needs clarification","icon":"CircleHelp"},{"id":"plan_in_review","label":"Plan in review","icon":"ClipboardCheck"},{"id":"in_progress","label":"In progress","icon":"Hammer"},{"id":"needs_help","label":"Needs help","icon":"LifeBuoy"},{"id":"in_review","label":"In review","icon":"GitPullRequest"},{"id":"completed","label":"Completed","icon":"BadgeCheck"},{"id":"canceled","label":"Canceled","icon":"CircleSlash"}],"transitions":{"todo":[{"toStatusId":"queued","actionLabel":"Queue"},{"toStatusId":"in_progress","actionLabel":"Start work"},{"toStatusId":"canceled","actionLabel":"Cancel"}],"queued":[{"toStatusId":"planning","actionLabel":"Start planning"},{"toStatusId":"canceled","actionLabel":"Cancel"}],"planning":[{"toStatusId":"plan_in_review","actionLabel":"Submit plan"},{"toStatusId":"needs_clarification","actionLabel":"Request clarification"},{"toStatusId":"canceled","actionLabel":"Cancel"}],"needs_clarification":[{"toStatusId":"planning","actionLabel":"Resume planning"},{"toStatusId":"canceled","actionLabel":"Cancel"}],"plan_in_review":[{"toStatusId":"in_progress","actionLabel":"Approve plan"},{"toStatusId":"planning","actionLabel":"Request changes"},{"toStatusId":"canceled","actionLabel":"Cancel"}],"in_progress":[{"toStatusId":"needs_help","actionLabel":"Request help"},{"toStatusId":"in_review","actionLabel":"Submit for review"},{"toStatusId":"canceled","actionLabel":"Cancel"}],"needs_help":[{"toStatusId":"in_progress","actionLabel":"Resume work"},{"toStatusId":"canceled","actionLabel":"Cancel"}],"in_review":[{"toStatusId":"in_progress","actionLabel":"Request changes"},{"toStatusId":"completed","actionLabel":"Approve"},{"toStatusId":"canceled","actionLabel":"Cancel"}],"completed":[],"canceled":[]}}', false, false, 'status', NOW(), NOW(), NULL);
INSERT INTO public.property (id, name, description, type, config, deletable, readonly, alias, "created_at", "updated_at", "deleted_at") VALUES ('property0004', 'Created At', NULL, 'datetime', NULL, false, true, 'createdAt', NOW(), NOW(), NULL);
INSERT INTO public.property (id, name, description, type, config, deletable, readonly, alias, "created_at", "updated_at", "deleted_at") VALUES ('property0005', 'Updated At', NULL, 'datetime', NULL, false, true, 'updatedAt', NOW(), NOW(), NULL);
INSERT INTO public.property (id, name, description, type, config, deletable, readonly, alias, "created_at", "updated_at", "deleted_at") VALUES ('property0006', 'Description', 'The description of the issue', 'rich_text', NULL, false, false, 'description', NOW(), NOW(), NULL);
INSERT INTO public.property (id, name, description, type, config, deletable, readonly, alias, "created_at", "updated_at", "deleted_at") VALUES ('property0007', 'Priority', 'Priority of the issue', 'select', '{"options":[{"id":"no-priority","name":"No Priority"},{"id":"low","name":"Low","icon":"SignalLow"},{"id":"medium","name":"Medium","icon":"SignalMedium"},{"id":"high","name":"High","icon":"SignalHigh"},{"id":"urgent","name":"Urgent","icon":"AlertTriangle"}]}', false, false, 'priority', NOW(), NOW(), NULL);
INSERT INTO public.property (id, name, description, type, config, deletable, readonly, alias, "created_at", "updated_at", "deleted_at") VALUES ('property0008', 'Category', 'Category of the issue', 'select', '{"options":[{"id":"hardware","name":"Hardware","icon":"HardDrive"},{"id":"software","name":"Software","icon":"AppWindow"},{"id":"network","name":"Network","icon":"Server"},{"id":"power_supply","name":"Power Supply","icon":"Zap"},{"id":"operational","name":"Operational","icon":"Hand"},{"id":"environmental","name":"Environmental","icon":"Globe"},{"id":"other","name":"Other","icon":"Waves"}]}', false, false, 'category', NOW(), NOW(), NULL);
INSERT INTO public.property (id, name, description, type, config, deletable, readonly, alias, "created_at", "updated_at", "deleted_at") VALUES ('property0009', 'Diagnosis', 'Diagnosis of the issue', 'select', '{"options":[{"id":"fan","name":"Fan","icon":"Fan"},{"id":"hashboard","name":"Hashboard","icon":"Gauge"},{"id":"control_board","name":"Control Board","icon":"ToggleLeft"},{"id":"psu","name":"PSU","icon":"BatteryCharging"},{"id":"temperature_sensor","name":"Temperature Sensor","icon":"Thermometer"},{"id":"firmware","name":"Firmware","icon":"HardDrive"},{"id":"overheating","name":"Overheating","icon":"Thermometer"},{"id":"other","name":"Other","icon":"Waves"}]}', false, false, 'diagnosis', NOW(), NOW(), NULL);
INSERT INTO public.property (id, name, description, type, config, deletable, readonly, alias, "created_at", "updated_at", "deleted_at") VALUES ('property0012', 'Assignee', 'Assignee', 'user', NULL, false, false, 'assignee', NOW(), NOW(), NULL);
INSERT INTO public.property (id, name, description, type, config, deletable, readonly, alias, "created_at", "updated_at", "deleted_at") VALUES ('property0013', 'Reporter', 'Reporter', 'user', NULL, false, false, 'reporter', NOW(), NOW(), NULL);
INSERT INTO public.property (id, name, description, type, config, deletable, readonly, alias, "created_at", "updated_at", "deleted_at") VALUES ('property1007', 'Declared At', NULL, 'datetime', NULL, false, false, 'declaredAt', NOW(), NOW(), NULL);

-- Insert system bot user
INSERT INTO "user" (id, name, email, "emailVerified", type, image, "createdAt", "updatedAt") VALUES ('bot_openapi', 'OpenAPI Bot', 'bot@openapi.local', true, 'bot', '/images/bot-avatar.svg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
