import { AIProviderId } from './ai-provider.types'

export const AI_PROVIDER_IDS: AIProviderId[] = [
  'openai',
  'anthropic',
  'google-generative',
  'google-vertex',
  'azure-openai',
  'xai',
  'deepseek',
  'mistral',
  'cohere',
  'bedrock',
  'groq',
  'cerebras',
  'together',
  'fireworks',
  'deepinfra',
  'baseten',
  'fal',
  'black-forest-labs',
  'luma',
  'replicate',
  'prodia',
  'elevenlabs',
  'assemblyai',
  'deepgram',
  'gladia',
  'lmnt',
  'revai',
  'hume',
  'vercel-ai-gateway',
  'open-responses',
  'huggingface',
  'perplexity',
  'moonshot',
]

export const DEFAULT_AI_PROVIDER: AIProviderId = 'openai'
