'use client'

import BoringAvatar from 'boring-avatars'
import * as React from 'react'

import { cn } from '@/lib/shadcn/utils'
import * as AvatarPrimitive from '@radix-ui/react-avatar'
import type { AvatarVariant } from './geometric-avatar'

const DEFAULT_COLORS = ['#264653', '#2a9d8f', '#e9c46a', '#f4a261', '#e76f51']

function Avatar({ className, ...props }: React.ComponentProps<typeof AvatarPrimitive.Root>) {
  return (
    <AvatarPrimitive.Root
      data-slot="avatar"
      className={cn('relative flex size-8 shrink-0 overflow-hidden rounded-full', className)}
      {...props}
    />
  )
}

function AvatarImage({ className, ...props }: React.ComponentProps<typeof AvatarPrimitive.Image>) {
  return (
    <AvatarPrimitive.Image data-slot="avatar-image" className={cn('aspect-square size-full', className)} {...props} />
  )
}

function AvatarFallback({ className, ...props }: React.ComponentProps<typeof AvatarPrimitive.Fallback>) {
  return (
    <AvatarPrimitive.Fallback
      data-slot="avatar-fallback"
      className={cn('bg-muted flex size-full items-center justify-center rounded-full', className)}
      {...props}
    />
  )
}

interface GeometricAvatarFallbackProps extends React.ComponentProps<typeof AvatarPrimitive.Fallback> {
  name: string
  variant?: AvatarVariant
  colors?: string[]
}

/**
 * Avatar fallback with geometric pattern generated by boring-avatars
 * Uses the user's name to generate a consistent, unique geometric pattern
 */
function GeometricAvatarFallback({
  name,
  variant = 'beam',
  colors = DEFAULT_COLORS,
  className,
  children,
  ...props
}: GeometricAvatarFallbackProps) {
  const size = 40

  return (
    <AvatarPrimitive.Fallback
      data-slot="avatar-fallback"
      className={cn('flex size-full items-center justify-center overflow-hidden rounded-full', className)}
      {...props}>
      {/* Use a wrapper with specific class to override button's [&_svg:not([class*='size-'])]:size-4 */}
      <div className="size-full [&_svg]:!size-full">
        <BoringAvatar size={size} name={name} variant={variant} colors={colors} />
      </div>
      {children}
    </AvatarPrimitive.Fallback>
  )
}

export { Avatar, AvatarImage, AvatarFallback, GeometricAvatarFallback }
